[project]
name = "befoerderungs_vorschlag"
version = "0.1.0"
description = "Beförderungsvorschläge aus FeuerOn Datenbank gem. Niedersächischer Feuerwehrverordnung prüfen"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
]
